restaurant_project/urls.py
from django.conf import settings 
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from restaurant_project import settings

from store import views


urlpatterns = [
    path('', views.index),
    path('store/', include('store.urls', namespace='store')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls import url
from django.urls import path
from django.conf.urls.static import static 
from restaurant_project import settings

from . import views

app_name="store"
urlpatterns = [
    path('list/', views.list, name="list"),
    path('<food_id>/', views.order, name='order'),
    #path('search/', views.search),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.core.files import File
import os

# Create your models here.
class Food(models.Model):
    reference = models.IntegerField(null=True)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255,null=True)
    price = models.IntegerField(null=True)
    picture = models.ImageField(upload_to='images')
    created_at = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name_plural="foods"

class Contact(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted = models.BooleanField(default=False)
    food = models.OneToOneField(Food, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE) #cascade delete the reservation done with contact
    def __str__(self):
        return self.contact.name

store/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, widget = forms.TextInput(attrs={'class':'form-control'}),
     required=True)

    address = forms.CharField(label='Address', max_length=100, widget = forms.TextInput(attrs={'class':'form-control'}),
     required=True)

store/views.py
from django.shortcuts import HttpResponse, render, get_object_or_404
from .forms import ContactForm
from .models import Food, Contact, Booking
from django.template import loader
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError

# Create your views here.

def index(request):
    #request foods
    foods=Food.objects.filter(available=True).order_by('-created_at')[:12]
    #then format the request.
    #note that we don't use food['title] anymore but food.title
    #because it's now an attribute
    formatted_foods=["<li>{}</li>".format(food.title) for food in foods]
    message="""<ul>{}</ul>""".format("\n".join(formatted_foods))

    template=loader.get_template('store/index.html')
    context={
        'foods':foods
    }
    return render(request, 'store/index.html', context)


def list(request):

    #request foods
    foods=Food.objects.filter(available=True).order_by('-created_at')[:12]
    #then format the request.
    #note that we don't use food['title] anymore but food.title
    #because it's now an attribute
    formatted_foods=["<li>{}</li>".format(food.title) for food in foods]
    message="""<ul>{}</ul>""".format("\n".join(formatted_foods))

    template=loader.get_template('store/list.html')
    context={
        'foods':foods
    }
    return render(request, 'store/list.html', context)



def order(request, food_id):
    food=get_object_or_404(Food, id=food_id)
    #food=Food.objects.filter(available=True)
    #context={
        #'food':food,
        #'title':foods.title,
        #'description':foods.description,
        #'price':foods.price,
        #'picture':foods.picture
    #}

    if request.method=='POST':
        form=ContactForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            address=form.cleaned_data['address']
            contact=Contact.objects.filter(name=name)
            try:
                contact=Contact.objects.get(name=name)
            except Contact.DoesNotExist:
                contact=Contact.objects.create(
                    name=name,
                    address=address
                )
            food=get_object_or_404(Food, pk=food_id)
            booking=Booking.objects.create(
                contact=contact,
                food=food
            )

            food.available=False
            food.save()
            context={
                'title':food.title
                        
            }

            return render(request, 'store/confirm.html', context)
    form=ContactForm()
    context={
        'form':form,
        'food':food
    }   
    return render(request, 'store/order.html', context)

store/templates/store/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show Meals For User</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'https://use.fontawesome.com/releases/v5.8.1/css/all.css' %}"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/admin add meal.css' %}">
    <link rel="stylesheet" href="{% static 'css/user show meals.css' %}">
    <link rel="stylesheet" href="{% static 'css/use fill order.css' %}">
</head>

<body>
    <!-- Start Header -->

    <header>
        <div class="container">
            <div class="logo">
                <img src="{% static 'images/logo1.png' %}">
                <span>FoodEat</span>
            </div>
            <ul class="links">
                <li><a href="#">Home</a></li>
                <li><a href="#">Menu</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Clients</a></li>
                <li><a href="#">Reservation</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
            <div class="clearfix"></div>
        </div>
    </header>

    <!-- End Header -->

    {% block content %}{% endblock %}

    <!-- Start Footer -->

    <footer>
        <div class="container">
            <p>2019 &copy; FoodEat. All Rights Reserved. Designed And Coded By Coding Team For <span>Coretabs</span>
                Competition</p>
            <ul class="links">
                <li><i class="fab fa-facebook-square fa-2x"></i></li>
                <li><i class="fab fa-twitter-square fa-2x"></i></li>
                <li><i class="fab fa-linkedin fa-2x"></i></li>
                <li><i class="fab fa-google-plus-square fa-2x"></i></li>
                <li><i class="fas fa-phone-square fa-2x"></i></li>
            </ul>
            <div class="clearfix"></div>
        </div>
    </footer>

    <!-- End Footer -->

    <script src="{% static 'js/jquery3.4.1.js' %}"></script>
    <script src="{% static 'js/admin orders.js' %}"></script>

</body>

</html>

store/templates/store/confirm.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<h1>Congratulations !!!!! The meal <em>{{food.title}}</em> is reserved for you now</h1>
<img src="{% static 'images/appetit.jpg' %}" style="width:50%; height: 50%; margin:auto 20% auto;">


{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}

<!-- Start Slider -->

    <!-- Start Menu -->

    <div class="slider">
            <div class="intro">
                <div class="container">
                    <h1>Welcome </h1>
                    <p> Online Food Services</p>
                    <p>New Flavours</p>
                </div>
            </div>
        </div>
    
        <!-- End Slider -->
    
        <!-- Start Menu -->
    
        <div class="menu">
            <div class="container">
                <h1>Restuarant Menu</h1>
                <div class="meal">
                    <div class="image">
                        <img src="{% static 'images/meal1.jpg' %}" alt="Burger">
                        <ul>
                            <li>Burgar</li>
                            <li>With Slices Of Meat &amp; Cheese</li>
                            <li>15 $</li>
                            <a href="{% url 'store:list' %}"><button>Show Meal</button></a>
                        </ul>
                    </div>
    
                    <div class="image">
                        <img src="{% static 'images/meal2.jpg' %}" alt="Grilled Chicken">
                        <ul>
                            <li>Grilled Chicken</li>
                            <li>With Avocado &amp; Lettuce</li>
                            <li>30 $</li>
                            <a href="{% url 'store:list' %}"><button>Show Meal</button></a>
                        </ul>
                    </div>
    
                    <div class="image">
                        <img src="{% static 'images/meal1.jpg' %}" alt="Steak">
                        <ul>
                            <li>Steak</li>
                            <li>With Fresh Vegetables &amp; Juice</li>
                            <li>35 $</li>
                            <a href="{% url 'store:list' %}"><button>Show Meal</button></a>
                        </ul>
                    </div>
                    <div class="image">
                        <img src="{% static 'images/meal2.jpg' %}" alt="Grilled Chicken">
                        <ul>
                            <li>Potato With Bechamel</li>
                            <li>With Spices &amp; Herbs</li>
                            <li>20 $</li>
                            <a href="{% url 'store:list' %}"><button>Show Meal</button></a>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    
        <!-- End Menu -->
    
        <!-- Start About-->
    
        <div class="about">
            <div class="container">
                <div class="manager">
                    <img src="{% static 'images/manager.jpg' %}">
                </div>
                <div class="about-us">
                    <h1>About Us</h1>
    
                    <div class="feature">
                        <div class="image">
                            <i class="fas fa-users fa-2x"></i>
                        </div>
                        <div class="text">
                            <h2>Professinal Manager &amp; Team </h2>
                            <p>Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam,
                                Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam
                            </p>
                        </div>
                    </div>
                    <div class="feature">
                        <div class="image">
                            <i class="fas fa-clock fa-2x"></i>
                        </div>
                        <div class="text">
                            <h2>Accurate Appointments</h2>
                            <p>Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam,
                                Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam
                            </p>
                        </div>
                    </div>
    
                    <div class="feature">
                        <div class="image">
                            <i class="fas fa-dollar-sign fa-2x"></i>
                        </div>
                        <div class="text">
                            <h2>Appropriate Prices</h2>
                            <p>Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam,
                                Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam
                            </p>
                        </div>
                    </div>
    
                    <div class="feature">
                        <div class="image">
                            <i class="fas fa-pepper-hot fa-2x"></i>
                        </div>
                        <div class="text">
                            <h2>Spicy Meals &amp; Multiple Choices</h2>
                            <p>Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam,
                                Lorem ipsum dolor sit amet, ea doming until epicuri iudicabit nam
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        </div>
    
        <!-- End About -->
    
        <!-- Start Clients -->
    
        <div class="clients">
            <h1>Our Clients</h1>
            <div class="container">
                <div class="client">
                    <div class="image">
                        <img src="{% static 'images/client1.png' %}">
                    </div>
                    <p>Tasty And Fresh Meals,I liKe Work Staff </p>
                </div>
    
                <div class="client">
                    <div class="image">
                        <img src="{% static 'images/client2.png' %}">
                    </div>
                    <p>I Like Their Respect For Appointments,And Their Accept Criticism </p>
                </div>
    
                <div class="client">
                    <div class="image">
                        <img src="{% static 'images/client3.png' %}">
                    </div>
                    <p>There Are Multiple Choices Of Meals,Spicy Food And Fresh Juice</p>
                </div>
            </div>
        </div>
    
        <!-- End Clients -->
    
    
    {% endblock %}

store/templates/store/list.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}

    <!-- Start Menu -->

    <div class="menu">
        <div class="container">
            <h1>Restuarant Menu</h1>
            <div class="meal">
                {% for food in foods %}
                    <div class="image">
                        <img src="{{ food.picture.url }}" alt=" {{ food.title }} ">
                        <ul>
                            <li>{{ food.title }}</li>
                            <li> {{ food.description }}</li></li>
                            <li>{{ food.price }} $</li>
                            <a href= "{% url 'store:order' food_id=food.id %}"><button>Order Now</button></a>
                        </ul>
                    </div>
                {% endfor %}
                
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <!-- End Menu -->

    <!-- Start About-->

    <div class="about">
        <div class="container">
            <div class="manager">
                <img src="{% static 'images/manager.jpg' %}">
            </div>
            
            <div class="clearfix"></div>
        </div>
    </div>

    <!-- End About -->

    <!-- Start Clients -->

    

    <!-- End Clients -->

    {% endblock %}

store/templates/store/order.html
{% extends 'store/base.html' %}
{% load static %}
 {% block content %}
            </div>
                <a href="{% url 'store:order' food_id=food.id %}" style="text-decoration: none;">
                    <h1>{{ food.title }}</h1>
                </a>
            <div class="clearfix"></div>
        
    <!-- End Header -->


    <!-- Start Reservation -->

    <div class="reservation">
        <div class="container">
            <a href="{% url 'store:order' food_id=food.id %}">
                <img class="image"  src="{{ food.picture.url }}" alt="{{ food.title }}">
            </a>
            <form name="reservation" action="{% url 'store:order' food_id=food.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}" class="control-label">Name</label>
                    {{form.name}}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}" class="control-label">Address</label>
                    {{form.address}}
                </div>
                <!--<input type="text" name="Full Name" value="" placeholder="Full Name" maxlength="30" id="name" required>
                <input type="text" name="Address" value="" placeholder="Address" maxlength="30" id="address" required>
                -->
                 <input type="submit" value="Reserve Now">
            </form>
        
        </div>
    </div>

    <!-- End Reservation -->

   {% endblock %}